### ISSUE TITLE
Feature request.  SSL option?

### ISSUE THREAD

**Issue by djh2020** [behance/docker-nginx#57]
Wouldn't it be a good idea to add a option to enable SSL and use port 443, rather than 8080.  I did this manually by adding my own shell script to `/etc/cont-init.d/` but I would have preferred it if I could have added an env variable `SSL_ENABLED=1`.

I'm no ngnix expert so although I got it to work, I am not sure I did it in the most effective / efficient way.  :-)

**Comment by bryanlatten** [comment]
@djh2020 there is an active PR for this, should be merged in the next couple days

**Comment by bryanlatten** [comment]
That said, IMHO the internal port != external port. We're doing everything possible to minimize the container capabilities, and not binding to a "privileged port" within the container means we can drop  `cap_net_bind_service`

**Comment by bryanlatten** [comment]
https://github.com/behance/docker-nginx/pull/48
