### ISSUE TITLE
Change the default value of ssl_session_cache?

### ISSUE THREAD

**Issue by HCHCHH** [behance/docker-nginx#64]
The Nginx [official document](http://nginx.org/en/docs/http/ngx_http_ssl_module.html) recommends to enable **ssl_session_cache** and set that to **shared:name:size**, which enables cache shared between all worker processes.

"To reduce the processor load it is recommended to set the number of worker processes equal to the number of processors, enable keep-alive connections,**enable the shared session cache**,"

I wonder whether the default setting need to be changed.  Thanks.

**Comment by bossjones** [comment]
@HCHCHH Hello, thank you for mentioning this optimization. There is a pull request currently open that will address this issue https://github.com/behance/docker-nginx/pull/48 . If someone chooses to enable SSL termination for local development, `ssl_session_cache` will be enabled by default along with some sane defaults.
