### ISSUE TITLE
Brotli support

### ISSUE THREAD

**Issue by yetanotherbhai** [behance/docker-nginx#72]
Is there a plan to support Brotli in docker-nginx image?
Brotli is supported by all the major browsers and there is great improvement in performance when using Brotli compressed resources.

**Comment by bryanlatten** [comment]
@yetanotherbhai its a fair question, brotli compression is quite good. I'm not against adding it, but curious on your use case? 
1. nginx is a reverse proxy for your backend language (node, php, java, etc)
2. nginx is serving static assets

In the former case, if you are delivering assets through your backend language, I recommend you push them instead to a blob store and front that with a CDN. Fastly for example, would then handle the brotli compression, or you can compress them in your language of choice before they enter the blob store.

The latter case would make sense, though I'd still recommend fronting these assets with a CDN (like above)

**Comment by yetanotherbhai** [comment]
@bryanlatten We have pre-compressed static assets in br and gzip. We are already serving them from CDN. 
Our service acts as a fallback to CDN which has nginx as a reverse proxy to our application.
This is where brotli support for serving pre-compressed static resources would be helpful.

**Comment by bryanlatten** [comment]
@yetanotherbhai makes sense. let me look into it, we also welcome contribution
